### ISSUE TITLE
Cannot deploy to IOS 

### ISSUE THREAD

**Issue by robbee** [beesearch/bee-mobile#5]
Hi Alex, when I deploy the app to ios 7, I can only have the left side menu (RH, Clients, Factures...) like a main page. I cannot slide or click to another view... Same on my ios emulator

When I run the app on my laptop browser, it's working like a charme ;-)

Thanks a lot.

IOS7 and XCode 5 on Mavericks

**Comment by BeeNoox** [comment]
It seems that the production task is broken :
`$ grunt build:production`

Try to build with :
`$ grunt build:development`
or
`$ grunt dev`

Then build with phonegap using `www` directory content.

**Comment by BeeNoox** [comment]
On a second thought, this app has never been run on an emulator (iOS nor Android).
Cordova plugins must be missing.
I will try to run the app on android emulator.

**Comment by robbee** [comment]
Hi Alex, it doesn't work any more when i deploy on phonegap build web site... I'm lost :-(  I've done all from scratch 

```
git clone ...
npm install
bower install
grunt build
mkdir platforms
phonegap build ios
grunt dev
```

and same probleme (in browser as well) : 

`Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8000/phonegap.js`

**Comment by robbee** [comment]
Hi Alex

I've tried this : http://ionicframework.com/getting-started/ and it's working find for me. Could you please check my setup on the wiki ? Tell me what i'm doing wrong ?

Thanks so much

**Comment by BeeNoox** [comment]
Hi,

This app has never been launched on a cordova-cli emulator/environment nor the ionic-cli.

It's at the time built using `grunt build`, zipping the `www` and update the code on phonegap build with the www.zip file.

It can be tested on a standard navigator by lanching `grunt dev` and launching `http://localhost:8000/` url.

At first sight, to enable the cordova-cli to emulate bee-mobile app, you need to: 
- change phonegap.js to cordova.js in src/views/app/app.tmpl.html
- install these cordova plugins:
  - org.apache.cordova.device: `cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-device.git`
  - org.apache.cordova.dialogs: `cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-dialogs.git`
  - org.apache.cordova.vibration: `cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-vibration.git`
    (please verify those cmd lines...)
- build the app: `grunt build`
- run cordova: `cordova build`

Bye ;)

**Comment by robbee** [comment]
Thanks Alex, but as i told you, even on a standard navigator with `grunt dev` the app still doesn't work. Ok for the teamviewer... ;-)

**Comment by BeeNoox** [comment]
Hi,

Not working either on mac os.
I'm going to make a plunkr and ask ionic community ;)

Bye

**Comment by BeeNoox** [comment]
Resolved

New ion- prefix was missing on ionic directives.
